/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/squirrel.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Squirrel(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/squirrel.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions,names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[0]].fadeOut(0.5);
    };
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Squirrelfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Squirrel" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_7">
                    <skinnedMesh name="Squirrel_01_-_Default_0" geometry={nodes['Squirrel_01_-_Default_0'].geometry} material={materials['01_-_Default']} skeleton={nodes['Squirrel_01_-_Default_0'].skeleton} />
                    <skinnedMesh name="Squirrel_01_-_Default_0_1" geometry={nodes['Squirrel_01_-_Default_0_1'].geometry} material={materials['Material.001']} skeleton={nodes['Squirrel_01_-_Default_0_1'].skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/squirrel.glb')
